# Generated by Django 3.2.18 on 2023-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('Linkedin_url', models.CharField(max_length=300)),
                ('image', models.ImageField(max_length=255, upload_to='images/%y/%m/%d/')),
            ],
        ),
    ]
